### ISSUE TITLE
Update Username on every login.

### ISSUE THREAD

**Issue by kywan** [wadahiro/keycloak-discord#11]
When a user updates his nickname on discord, keycloak should update it too.

ps : why not do it with the email too ?!

**Comment by williamhatcher** [comment]
While I haven't tried this, I think you can do this under the "Mappers" section.
Create a new mapper and set the "Sync mode override" to "force"
![image](https://user-images.githubusercontent.com/24600763/133949102-f25f582f-6dce-4613-8f9e-18ca2f16969d.png)

**Comment by wadahiro** [comment]
@williamhatcher Thank you for your comment.
I have confirmed that we can update it every time the user login using Mapper with `force` setting.
