### ISSUE TITLE
Have to approve application on every login

### ISSUE THREAD

**Issue by Getty** [wadahiro/keycloak-discord#12]
Probably this is just a PEBKAC, but even tho I can login/link via Discord, I still have to approve the application every single time new, asking for the scopes. I do have Store Tokens activated.

**Comment by williamhatcher** [comment]
Set Prompt to `none` in the settings.

**Comment by wadahiro** [comment]
Discord seemed to support `none`, which is one of the `prompt` parameters in [OIDC's authentication request](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest).
As @williamhatcher commented, please set prompt to none as shown in the attached image:

![image](https://user-images.githubusercontent.com/28739/134769891-2f40a4ce-6d3a-4af7-a4b3-bf3d31bf60e7.png)

But as a precaution, the spec expects an error to be returned if it is not authenticated. 
Keep in mind that the current Discord shows the login screen when not authenticated, but that may change in the future.

> An error is returned if an End-User is not already authenticated or the Client does not have pre-configured consent for the requested Claims or does not fulfill other conditions for processing the request.

**Comment by Versoo** [comment]
> Set Prompt to `none` in the settings.

I have the same problem in version 0.6.0 and Keycloak 26.2.0 but unfortunately there is no option to set the 'prompt' field.

Any sugestions?
