### ISSUE TITLE
404 on last update

### ISSUE THREAD

**Issue by kywan** [wadahiro/keycloak-discord#19]
On
Keycloak Server Version | 17.0.1
Keycloak-discord version | 0.4.0

When i try to add Discord provider i got that error.
![image](https://user-images.githubusercontent.com/16059072/163654988-d029e5f3-c170-4e7c-bff6-241f114da117.png)

On my network i have a 404 on that URL : 
/auth/resources/iu7m3/admin/keycloak/partials/realm-identity-provider-discord.html

**Comment by bman46** [comment]
Also have this issue.

**Comment by bman46** [comment]
Appears to be an issue with backwards compatibility with Keycloak Wildfly. Works fine with Keycloak Quarkus.

**Comment by wadahiro** [comment]
Yes, It is for Quarkus base from v0.4.0.
For Wildfly, please try [v0.3.1](https://github.com/wadahiro/keycloak-discord/releases/tag/v0.3.1).
