### ISSUE TITLE
Keycloak 20 - How to broker identity

### ISSUE THREAD

**Issue by antonionardella** [wadahiro/keycloak-discord#30]
Hello, I have set the identity provider as follows
![image](https://user-images.githubusercontent.com/7383572/214649219-9c78a532-97c8-4e1b-8e58-a7e6064384c6.png)

But it is still asking the user to update the account information after logging in
![image](https://user-images.githubusercontent.com/7383572/214648957-94e609dd-e68f-4e41-a03c-363efdb92d64.png)

Client configuration
![image](https://user-images.githubusercontent.com/7383572/214649038-0802de89-9f69-43d2-8b4d-7b49a0242872.png)
![image](https://user-images.githubusercontent.com/7383572/214649100-cb4393e3-1693-464a-811d-a26950a75464.png)

Can anyone help me understand how to use Keycloak to broker Discord's identity without saving the information?
Thanks

**Comment by laxadeR** [comment]
Might not be exactly what you want, but you can just disable the "Review Profile" step from the Authentication flow configured to be used by discord provider on first login. If you only want to be able to link/login to existing Keycloak accounts, you can also disable user creation and confirm link existing account like this.
![image](https://user-images.githubusercontent.com/29030191/216698607-39778a92-d255-4cad-b45b-8cbf9dca60cc.png)

**Comment by Tawmy** [comment]
Alternatively to this, you can enable the declarative-user-profile feature (this is still in preview!). You can find the configuraiton option here: https://www.keycloak.org/server/all-config?q=features.

When this is enabled, you can toggle "User Profile Enabled" in your realm settings, then use the "User profile" tab to remove first and last name fields, or make them non-mandatory.

You'd then be able to keep the non-modified authentication flow while avoiding the user having to enter their first and last name.

**Comment by wadahiro** [comment]
> But it is still asking the user to update the account information after logging in

Asking for a user profile setting on first login is the default behavior of Keycloak's Broker feature and has nothing to do with this extension.

This behavior can be changed by configuring the "first broker login" flow. If you check the "Settings" in the "Review Profile config", you will see that "Update Profile on First Login" is "missing". By setting this to "off", you should get the behavior you expect.

![Screen Shot 2023-08-11 at 15 43 53](https://github.com/wadahiro/keycloak-discord/assets/28739/ecf6dbbe-c5d2-4ca1-805b-84b12e3e33d5)
