### ISSUE TITLE
Unexpected Server Error while adding Identity Provider

### ISSUE THREAD

**Issue by P3RF3CTION** [wadahiro/keycloak-discord#4]
While adding the Identity Provider an error shows up.
Full Log can be provided if necessary. 
` ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-116) Uncaught server error: java.lang.AbstractMethodError: Method org/keycloak/social/discord/DiscordIdentityProviderFactory.createConfig()Lorg/keycloak/models/IdentityProviderModel; is abstract
`

**Comment by wadahiro** [comment]
@P3RF3CTION Thank you for the report.
It is due to a new interface method which was introduced in keycloak 9.0.2 (for [KEYCLOAK-12192](https://github.com/keycloak/keycloak/commit/2f489a41ebd06eb14197f8a66afae86ac1397f42)).
To resolve this problem, I will release a new version.

**Comment by P3RF3CTION** [comment]
Thank you for the new Release.
I am testing it right now!  😄

**Comment by P3RF3CTION** [comment]
Problem solved thank you for the fast support!
