### ISSUE TITLE
Upgrade keycloak to 23

### ISSUE THREAD

**Issue by g-jozsef** [wadahiro/keycloak-discord#44]
Hi!

[wadahiro](https://github.com/wadahiro/keycloak-discord/commits?author=wadahiro) is this project still maintained?

The [latest release](https://github.com/wadahiro/keycloak-discord/releases/tag/v0.5.0) has support for Keycloak v22 but v23 released 2 months ago, do you have any plans to upgrade this extension to support v23?

Related open PRs from dependabot
https://github.com/wadahiro/keycloak-discord/pull/40
https://github.com/wadahiro/keycloak-discord/pull/42

**Comment by Alfagun74** [comment]
see #45

**Comment by g-jozsef** [comment]
Thanks, closing this as it's superseded by https://github.com/wadahiro/keycloak-discord/issues/45
