### ISSUE TITLE
Upgrade to Keycloak 24

### ISSUE THREAD

**Issue by Alfagun74** [wadahiro/keycloak-discord#45]
Hi!

[wadahiro](https://github.com/wadahiro/keycloak-discord/commits?author=wadahiro) is this project still maintained?

The [latest release](https://github.com/wadahiro/keycloak-discord/releases/tag/v0.5.0) has support for Keycloak v22 but v24 released this week. Do you have any plans to upgrade this extension to support v24?

**Comment by Alfagun74** [comment]
I got it working with 24.0.1 without any issues so far actually.

**Comment by sahya** [comment]
@Alfagun74 @@g-jozsef 
Hi guys, I inform you this product was updated to be suite keycloak 26.0.5 by wadahiro-san. Could you confirm your environment?
https://github.com/wadahiro/keycloak-discord/releases
![image](https://github.com/user-attachments/assets/5b66cbe7-03f6-4c04-b70e-01b5a1f78516)

**Comment by Alfagun74** [comment]
hi @sahya, @wadahiro & @g-jozsef, i can confirm i have got it to work with Version 26.0.5 of Keycloak. Keep up the good work and thank you guys so much!
